import type { Platform } from "./types";
import {
  INTEGRATION_TYPES,
  PLATFORM_STATUSES,
  PLATFORM_TYPES,
  SETTLEMENT_CYCLES,
} from "./constants";

export const platforms: Platform[] = [
  {
    id: 1,
    platformName: "네이버 스마트스토어",
    platformCode: "NAVER_STORE",
    type: "오픈마켓",
    integrationType: "API",
    managerName: "김민수",
    managerPhone: "010-1234-5678",
    settlementCycle: "월말 정산",
    commissionRate: 3.74,
    status: "사용중",
    createdAt: "2025-03-15",
    updatedAt: "2025-05-23",
  },
  {
    id: 2,
    platformName: "쿠팡",
    platformCode: "COUPANG",
    type: "종합몰",
    integrationType: "API",
    managerName: "이서연",
    managerPhone: "010-2345-6789",
    settlementCycle: "주간 정산",
    commissionRate: 10.8,
    status: "사용중",
    createdAt: "2025-03-18",
    updatedAt: "2025-05-22",
  },
  {
    id: 3,
    platformName: "지마켓",
    platformCode: "GMARKET",
    type: "오픈마켓",
    integrationType: "CSV",
    managerName: "박지훈",
    managerPhone: "010-3456-7890",
    settlementCycle: "월말 정산",
    commissionRate: 12.0,
    status: "사용중",
    createdAt: "2025-03-20",
    updatedAt: "2025-05-20",
  },
  {
    id: 4,
    platformName: "옥션",
    platformCode: "AUCTION",
    type: "오픈마켓",
    integrationType: "CSV",
    managerName: "최유진",
    managerPhone: "010-4567-8901",
    settlementCycle: "월말 정산",
    commissionRate: 12.0,
    status: "사용중",
    createdAt: "2025-03-22",
    updatedAt: "2025-05-19",
  },
  {
    id: 5,
    platformName: "11번가",
    platformCode: "ELEVEN_ST",
    type: "오픈마켓",
    integrationType: "API",
    managerName: "정태민",
    managerPhone: "010-5678-9012",
    settlementCycle: "월말 정산",
    commissionRate: 13.0,
    status: "사용중",
    createdAt: "2025-03-25",
    updatedAt: "2025-05-18",
  },
  {
    id: 6,
    platformName: "자사몰",
    platformCode: "OWN_MALL",
    type: "자사몰",
    integrationType: "API",
    managerName: "오세훈",
    managerPhone: "010-7890-1234",
    settlementCycle: "익월 말 정산",
    commissionRate: 0,
    status: "사용중",
    createdAt: "2025-04-01",
    updatedAt: "2025-05-17",
  },
  {
    id: 7,
    platformName: "오프라인 매장",
    platformCode: "OFFLINE_STORE",
    type: "오프라인",
    integrationType: "수동",
    managerName: "한지민",
    managerPhone: "010-8901-2345",
    settlementCycle: "월말 정산",
    commissionRate: 0,
    status: "비활성",
    createdAt: "2025-04-05",
    updatedAt: "2025-05-10",
  },
];

export const platformStatuses = PLATFORM_STATUSES;
export const platformTypes = PLATFORM_TYPES;
export const integrationTypes = INTEGRATION_TYPES;
export const settlementCycles = SETTLEMENT_CYCLES;
